# Add specified repository into sources list.
# {{ansible_distribution_version}}=$(lsb_release -cs) 变量转换成 bionic,xenial,focal等。有待进一步优化
# {{ansible_machine}}=$(arch) 变量转成 x86_64
- apt_repository:
    repo: deb http://archive.canonical.com/ubuntu $(lsb_release -cs) partner $(arch)
    repo: deb http://archive.canonical.com/ubuntu {{ansible_distribution_version}} partner {{ansible_machine}}
    #http://mirror.centos.org/centos/6/os/x86_64/
    repo: http://mirror.centos.org/centos/$releasever/os/$basearch/
    state: present
