# 避免重复下载一个大的压缩文件包
- name: Ansible check file exists
  shell: if [ ! $(ls /data/wwwroot/knowage | grep Knowage-*.sh) ]; then echo "need_download";else echo "downloaded";fi
  register: result

- name: Download Knowage, it have 2G, need 10 minutes
  unarchive:
    src: "{{knowage_download_url}}"
    dest: "/data/wwwroot/knowage"
    remote_src: yes
    mode: 0750
  when: result.stdout == "need_download"
  
  

# 变量testpath是路径信息"/testdir"，判断路径是否存
- debug:
    msg: "file exist"
  when: testpath is exists
  #when: testpath is not exists
 
# 判断是否包含"."号 
- name: replace
  debug: msg="323.2323"
  when: teststr is match("[0-9]+\.[0-9]+")

# 判断变量：定义，未定义，none
vars:
  testvar: "test"
  testvar1:
tasks:
- debug:
    msg: "Variable is defined"
  when: testvar is defined
- debug:
    msg: "Variable is undefined"
  when: testvar2 is undefined
- debug:
    msg: "The variable is defined, but there is no value"
  when: testvar1 is none
